// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnqrendpjvjyztktrnpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxucXJlbmRwanZqeXp0a3RybnBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTIzOTksImV4cCI6MjA1ODk4ODM5OX0.66zQKz4R7EK22S2iAB-olpquhsjbwNw-tqmmqEeWZF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);